# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-19 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=150)),
                ('insurance', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('mot', models.IntegerField()),
                ('phone_no', models.CharField(max_length=150)),
                ('lastMotDate', models.CharField(max_length=150)),
                ('model_name', models.CharField(max_length=150)),
            ],
        ),
    ]
